Complete / verify Dutch translations
primefaces/primelocale pull request #94
Opened 2023-07-31 17:57 UTC by jepsar

2023-07-31 18:04 UTC, melloware requested changes

2023-07-31 18:04 UTC, melloware commented on nl.json
> +         "pageLabel": "{page}",
I just started making this "Page 5" so the screen reader reads it Page 5 and not just "5".

2023-07-31 18:10 UTC, merged

2023-10-18 15:34 UTC, jepsar commented
> Added new label `"now": "Now",` to the English file if you don't mind adding it to yours?

Sorry, I'm not following. What do you mean with "yours"?

2023-10-18 15:38 UTC, melloware commented
Sorry i took care of it by "yours" i mean "NL" translation 😄